#ifndef __SAVM_ERROR_H_
#define __SAVM_ERROR_H_ 1

typedef enum {
	SAVM_ERROR_NONE = 0,
	SAVM_ERROR_MEM,
	SAVM_ERROR_NOTMAPPED,
	SAVM_ERROR_MAPPED,
	SAVM_ERROR_INVAL_ADDR,
	SAVM_ERROR_INVAL_INT,
	SAVM_ERROR_INVAL_FILE,
	SAVM_ERROR_DOUBLE_FAULT
} savm_error_e;

#endif
